### ISSUE TITLE
Consul integration

### ISSUE THREAD

**Issue by peterlamar** [CiscoCloud/kubernetes-ansible#55]
As a Tenant, I can find K8s services via Consul so that I may integrate my non container services easily with k8s

@saswatp explained this use case to me and it seemed compelling. Consul sounds useful as a one-source of truth for the application's services. 

Does this overlap with K8s roadmap or featureset? 
Are there possible gotcha's with this idea?

**Comment by altvnk** [comment]
There is a huge thread on k8s. Many people voted for Consul as service discovery in k8s. Trying to find that issue.

**Comment by stevendborrelli** [comment]
One of the easiest things we can do is just port kube2sky to use consul: https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/kube2sky/kube2sky.go

That way etcd is not touched, and since it is an add on, it's not a major part of k8s. Downside is that consul does not yet support the nested dns naming that kube2sky uses. I think 0.6 will fix it.

**Comment by altvnk** [comment]
This is a good idea.
Btw nested naming was the biggest issue for adopting consul.

**Comment by altvnk** [comment]
Oh, i missed, that issue was about global KV for kubernetes.
